In [2]:
import torch
from transformers import *

In [56]:
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased', do_lower_case=False)
model = BertModel.from_pretrained('/dev/bert/')
input_ids = torch.tensor([101, 108, 31278, 90939, 70325, 196, 199, 71436, 10107, 29190, 10107, 106, 16680, 68314, 10153, 17015, 15934, 10104, 108, 10233, 12396, 14945, 10107, 10858, 11405, 13600, 13597, 169, 57343, 64482, 119, 119, 119, 100, 11741, 16381, 10109, 68830, 10110, 20886, 108, 10233, 11127, 21768, 100, 14120, 131, 120, 120, 188, 119, 11170, 120, 12132, 10884, 10157, 11490, 12022, 10113, 10731, 10729, 11565, 14120, 131, 120, 120, 188, 119, 11170, 120, 162, 11211, 11703, 12022, 11211, 10240, 44466, 100886, 102]).unsqueeze(0)  # Batch size 1
outputs = model(input_ids)
last_hidden_states = outputs[0][0][0]  # The last hidden-state is the first element of the output tuple

In [58]:
tokenizer.decode([101, 108, 31278, 90939, 70325, 196, 199, 71436, 10107, 29190, 10107, 106, 16680, 68314, 10153, 17015, 15934, 10104, 108, 10233, 12396, 14945, 10107, 10858, 11405, 13600, 13597, 169, 57343, 64482, 119, 119, 119, 100, 11741, 16381, 10109, 68830, 10110, 20886, 108, 10233, 11127, 21768, 100, 14120, 131, 120, 120, 188, 119, 11170, 120, 12132, 10884, 10157, 11490, 12022, 10113, 10731, 10729, 11565, 14120, 131, 120, 120, 188, 119, 11170, 120, 162, 11211, 11703, 12022, 11211, 10240, 44466, 100886, 102])

'[CLS] # ENVIVO | ¡ Buenas noches! Comienza una nueva edición de # 24HorasCentral junto a Iván Núñez... [UNK] Sigue la señal en vivo # 24Play [UNK] https : / / t. co / mi3yDUaS2F https : / / t. co / Y6qU6gwdCL [SEP]'

In [59]:
last_hidden_states

tensor([-3.1164e-01, -4.9567e-02, -1.8035e-01,  2.7875e-02,  9.6286e-02,
        -1.1317e-01,  3.8975e-01,  5.9788e-02, -1.8645e-01, -2.5343e-01,
         1.2640e-01,  1.8534e-01,  3.6691e-01,  2.5003e-01, -7.2783e-01,
         2.4973e-02,  1.1377e-02,  3.5736e-01,  1.5089e-01,  8.0563e-02,
         9.2578e-03,  1.8207e-01, -1.3513e-01, -1.5369e-02, -2.0341e-01,
        -2.1747e-01,  1.8431e-02,  4.8761e-01,  5.4433e-01,  2.9416e-01,
         3.3940e-01,  1.9408e-01, -1.2509e-01,  9.5964e-02,  1.4272e-01,
        -2.6225e-01, -1.8296e+00,  1.1323e-02, -1.1208e-01, -3.4605e-02,
         4.4772e-02,  2.0283e-01, -1.3155e-01, -1.3792e-01,  4.2419e-02,
         1.2304e+00,  2.0679e-01,  3.3012e-01,  1.1707e+00,  7.9489e-02,
        -1.4379e-01, -5.4192e-01, -2.1640e-01, -1.4817e+00, -4.4211e-02,
         2.4996e-01,  1.5661e-02,  6.0621e-02, -1.8868e-01, -1.8413e-01,
         7.2964e-03, -3.6828e-02,  2.6129e-01,  7.8231e-03,  2.2604e-01,
         5.6580e-02, -1.7340e-01, -7.0535e-02, -2.3

In [3]:
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased', do_lower_case=False)
model = BertModel.from_pretrained('/dev/bert/')

In [4]:
input_ids = torch.tensor([101, 108]).unsqueeze(0)  # Batch size 1
outputs = model(input_ids)
last_hidden_states = outputs[0][0][0]  # The last hidden-state is the first element of the output tuple

In [6]:
input_ids = torch.tensor(tokenizer.encode("[CLS] My sentence")).unsqueeze(0)
outputs = model(input_ids)
embeddings_of_last_layer = outputs[0]
cls_embeddings = embeddings_of_last_layer[0]

In [8]:
embeddings_of_last_layer

tensor([[[ 0.3212, -0.0544, -0.0861,  ...,  0.7931, -0.3903, -0.0120],
         [ 0.3208, -0.0570, -0.0851,  ...,  0.7936, -0.3919, -0.0130],
         [ 0.3468, -0.2333, -0.0710,  ...,  0.6953, -0.6291, -0.1370],
         [ 0.2627, -0.3894, -0.3073,  ...,  0.9721, -0.4724, -0.2921],
         [ 0.2843, -0.2475,  0.1256,  ...,  0.7671, -0.4177, -0.0446]]],
       grad_fn=<NativeLayerNormBackward>)

In [7]:
cls_embeddings[0]

tensor([ 3.2121e-01, -5.4417e-02, -8.6102e-02,  1.6083e-01, -1.2724e-01,
        -1.1863e-02, -3.9340e-01,  2.0404e-01,  1.0924e-01, -2.6062e-01,
         5.3292e-01, -1.6562e-01,  6.3398e-02, -1.1186e-01, -4.1014e-01,
         1.0758e-02, -5.5582e-02,  7.6777e-01,  4.5858e-01,  6.6396e-01,
         8.7407e-02,  3.2365e-01, -3.0692e-01,  9.4165e-03,  4.5095e-01,
        -2.1449e-01,  8.1025e-02, -2.0580e-01,  1.9197e-01,  7.4378e-02,
         5.2771e-01,  3.0615e-01, -1.5516e-01,  5.7969e-01,  3.9827e-01,
         3.7909e-02, -8.0676e-01, -1.9927e-01, -3.1221e-01, -4.4068e-01,
        -3.3501e-01, -1.3054e-01,  3.9339e-01,  2.7643e-01,  4.4010e-01,
         7.1446e-01,  2.0268e-01, -9.1150e-02,  4.2229e-01, -8.6419e-01,
         5.4797e-02, -7.6668e-01,  7.8603e-01, -1.3261e+00,  4.0646e-01,
         4.3429e-01,  2.8713e-03, -1.3567e-01, -1.9692e-01,  2.4281e-01,
         4.0501e-01,  7.5429e-01,  5.1152e-02, -3.6600e-01, -5.5143e-01,
        -5.5313e-01, -7.7702e-02,  1.8873e-01, -2.6

In [18]:
input_ids.shape

torch.Size([1, 79])

In [44]:
last_hidden_states[0].shape

torch.Size([79, 768])

In [5]:
last_hidden_states

tensor([ 2.6847e-01, -5.7668e-01,  1.8359e-01,  1.1416e-01,  8.5621e-02,
         1.0435e-01,  2.6839e-02,  9.4382e-01, -5.5169e-01,  3.6284e-01,
         1.9132e-01,  7.8991e-01,  2.5428e-01,  4.9141e-01,  2.7798e-01,
        -2.1794e-01,  8.7347e-01, -1.7157e-01, -6.0503e-01,  7.7051e-01,
        -7.8044e-01, -6.4269e-02,  8.8347e-01, -1.6645e-01,  1.4419e-01,
         1.1550e+00, -7.6593e-01, -6.0788e-01,  3.1496e-01, -3.2022e-01,
        -5.0232e-01, -5.0274e-01,  3.3638e-03,  3.2646e-01,  1.1946e-01,
        -8.0921e-02,  1.6555e-02,  5.6689e-01,  6.9221e-01,  8.3903e-02,
         1.0178e-03,  2.4890e-01, -8.7362e-02, -3.2178e-01, -8.0344e-02,
        -3.2293e-01,  3.9753e-01,  2.2282e-01, -3.5801e-01,  9.8585e-01,
         5.6671e-02, -1.5473e-01, -1.7192e-01,  1.1102e-01, -9.4336e-01,
        -1.8301e-02, -2.4016e-01,  4.5593e-01,  6.9304e-01,  3.2511e-01,
        -2.6158e-01, -2.1500e-02, -1.4318e-01, -8.7951e-02, -5.5176e-01,
        -1.1372e-01, -1.9628e-01,  2.6121e-01,  1.2

In [27]:
mean = last_hidden_states.mean(dim=1)

In [28]:
mean.shape

torch.Size([1, 768])

In [24]:
mean

tensor([[ 6.4805e-02, -4.2387e-01,  2.5238e-02, -4.5042e-02,  2.8164e-01,
          1.2641e-01,  4.8142e-02,  4.2612e-01, -9.0083e-02,  2.7727e-01,
          5.1189e-01,  1.4792e-02,  1.1726e-01,  3.6286e-01,  3.8785e-01,
         -8.8801e-02,  4.5374e-01,  2.1557e-01, -3.9564e-01,  4.0138e-01,
         -8.2246e-01,  8.9695e-02,  7.3050e-01, -3.4167e-01,  2.1496e-01,
          6.6250e-01, -4.7407e-01, -3.1473e-01,  2.2099e-01, -2.9732e-01,
         -4.0190e-01, -1.1781e-01, -1.4600e-01,  2.1357e-01, -1.3338e-02,
         -1.6685e-01,  1.7888e-01,  6.5907e-02,  3.6534e-02,  6.4048e-02,
          3.4789e-01,  2.4846e-01,  1.1392e-01, -1.7823e-01, -2.4612e-01,
         -1.1902e-01,  6.2179e-02,  3.8479e-01, -2.2683e-03,  7.3421e-01,
          1.9867e-01, -1.7005e-01, -5.8061e-01,  6.1885e-02, -4.4230e-01,
         -7.4421e-02, -1.6320e-01, -5.0988e-02,  4.6794e-01,  4.5912e-01,
         -1.5221e-01,  9.3750e-02, -1.7329e-01,  9.6182e-02, -4.0823e-01,
          6.4527e-02, -3.6043e-01,  1.

In [34]:
outputs[0]

tensor([[[ 0.2685, -0.5767,  0.1836,  ..., -0.0248,  0.0143, -0.3322],
         [-0.1389, -0.2711, -0.1331,  ...,  0.1358,  0.2481, -0.6525]]],
       grad_fn=<NativeLayerNormBackward>)

In [37]:
model(input_ids).get_output_embeddings()

AttributeError: 'tuple' object has no attribute 'get_output_embeddings'