In [2]:
import torch
from transformers import *

In [3]:
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased', do_lower_case=False)
model = BertModel.from_pretrained('/dev/bert/')
input_ids = torch.tensor([101, 108, 31278, 90939, 70325, 196, 199, 71436, 10107, 29190, 10107, 106, 16680, 68314, 10153, 17015, 15934, 10104, 108, 10233, 12396, 14945, 10107, 10858, 11405, 13600, 13597, 169, 57343, 64482, 119, 119, 119, 100, 11741, 16381, 10109, 68830, 10110, 20886, 108, 10233, 11127, 21768, 100, 14120, 131, 120, 120, 188, 119, 11170, 120, 12132, 10884, 10157, 11490, 12022, 10113, 10731, 10729, 11565, 14120, 131, 120, 120, 188, 119, 11170, 120, 162, 11211, 11703, 12022, 11211, 10240, 44466, 100886, 102]).unsqueeze(0)  # Batch size 1
outputs = model(input_ids)
last_hidden_states = outputs[0]  # The last hidden-state is the first element of the output tuple

In [19]:
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased', do_lower_case=False)
model = BertModel.from_pretrained('/dev/bert/')
input_ids = torch.tensor([101, 108]).unsqueeze(0)  # Batch size 1
outputs = model(input_ids)
last_hidden_states = outputs[0]  # The last hidden-state is the first element of the output tuple

In [ ]:
input_ids = torch.tensor(tokenizer.encode("[CLS] My sentence")).unsqueeze(0)
outputs = model(input_sentence)
embeddings_of_last_layer = outputs[0]
cls_embeddings = embeddings_of_last_layer[0]

In [18]:
input_ids.shape

torch.Size([1, 79])

In [20]:
last_hidden_states.shape

torch.Size([1, 2, 768])

In [21]:
last_hidden_states

tensor([[[ 0.2685, -0.5767,  0.1836,  ..., -0.0248,  0.0143, -0.3322],
         [-0.1389, -0.2711, -0.1331,  ...,  0.1358,  0.2481, -0.6525]]],
       grad_fn=<NativeLayerNormBackward>)

In [27]:
mean = last_hidden_states.mean(dim=1)

In [28]:
mean.shape

torch.Size([1, 768])

In [24]:
mean

tensor([[ 6.4805e-02, -4.2387e-01,  2.5238e-02, -4.5042e-02,  2.8164e-01,
          1.2641e-01,  4.8142e-02,  4.2612e-01, -9.0083e-02,  2.7727e-01,
          5.1189e-01,  1.4792e-02,  1.1726e-01,  3.6286e-01,  3.8785e-01,
         -8.8801e-02,  4.5374e-01,  2.1557e-01, -3.9564e-01,  4.0138e-01,
         -8.2246e-01,  8.9695e-02,  7.3050e-01, -3.4167e-01,  2.1496e-01,
          6.6250e-01, -4.7407e-01, -3.1473e-01,  2.2099e-01, -2.9732e-01,
         -4.0190e-01, -1.1781e-01, -1.4600e-01,  2.1357e-01, -1.3338e-02,
         -1.6685e-01,  1.7888e-01,  6.5907e-02,  3.6534e-02,  6.4048e-02,
          3.4789e-01,  2.4846e-01,  1.1392e-01, -1.7823e-01, -2.4612e-01,
         -1.1902e-01,  6.2179e-02,  3.8479e-01, -2.2683e-03,  7.3421e-01,
          1.9867e-01, -1.7005e-01, -5.8061e-01,  6.1885e-02, -4.4230e-01,
         -7.4421e-02, -1.6320e-01, -5.0988e-02,  4.6794e-01,  4.5912e-01,
         -1.5221e-01,  9.3750e-02, -1.7329e-01,  9.6182e-02, -4.0823e-01,
          6.4527e-02, -3.6043e-01,  1.

In [34]:
outputs[0]

tensor([[[ 0.2685, -0.5767,  0.1836,  ..., -0.0248,  0.0143, -0.3322],
         [-0.1389, -0.2711, -0.1331,  ...,  0.1358,  0.2481, -0.6525]]],
       grad_fn=<NativeLayerNormBackward>)

In [37]:
model(input_ids).get_output_embeddings()

AttributeError: 'tuple' object has no attribute 'get_output_embeddings'